name: titanic
channels:
  - defaults
dependencies:
  - python>=3.8,<3.9
  - pip
  - pip:
      - numpy
      - pandas
      - scikit-learn
      - matplotlib
      - seaborn

      - mlflow
      - hyperopt
      - shap

      - python-box
      - python-dotenv
      - pyyaml
      - envyaml
