experiment:
  name: MyAutoML/Titanic

model:
  name: titanic

training:
  max_evals: 2

evaluation:
  primary_metric: roc_auc_cv
  metrics:
    - roc_auc
    - accuracy
  shap_analysis: True

prediction:
  stage: Production
